// <auto-generated />
using System;
using Dfe.Identifiers.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dfe.Identifiers.Infrastructure.Migrations.Academisation
{
    [DbContext(typeof(AcademisationContext))]
    [Migration("20240423142452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dfe.Identifiers.Domain.Models.ConversionProject", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("ApplicationReferenceNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ApplicationReferenceNumber");

                    b.Property<int?>("FormAMatProjectId")
                        .HasColumnType("int")
                        .HasColumnName("FormAMatProjectId");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SchoolName");

                    b.Property<string>("SponsorReferenceNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SponsorReferenceNumber");

                    b.Property<string>("TrustReferenceNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrustReferenceNumber");

                    b.Property<int>("URN")
                        .HasColumnType("int")
                        .HasColumnName("Urn");

                    b.HasKey("Id");

                    b.HasIndex("FormAMatProjectId");

                    b.ToTable("Project", "academisation");
                });

            modelBuilder.Entity("Dfe.Identifiers.Domain.Models.FormAMatProject", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("ApplicationReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ApplicationReference");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReferenceNumber");

                    b.HasKey("Id");

                    b.ToTable("FormAMatProject", "academisation");
                });

            modelBuilder.Entity("Dfe.Identifiers.Domain.Models.TransferProject", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<long?>("OutgoingTrustUKPRN")
                        .HasColumnType("bigint")
                        .HasColumnName("OutgoingTrustUkprn");

                    b.Property<string>("ProjectReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectReference");

                    b.Property<int>("URN")
                        .HasColumnType("int")
                        .HasColumnName("Urn");

                    b.HasKey("Id");

                    b.ToTable("TransferProject", "academisation");
                });

            modelBuilder.Entity("Dfe.Identifiers.Domain.Models.ConversionProject", b =>
                {
                    b.HasOne("Dfe.Identifiers.Domain.Models.FormAMatProject", "FormAMatProject")
                        .WithMany()
                        .HasForeignKey("FormAMatProjectId");

                    b.Navigation("FormAMatProject");
                });
#pragma warning restore 612, 618
        }
    }
}
