version: "3.8"
services:
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "./docker-entrypoint.sh dotnet Dfe.Identifiers.Api.dll"
    ports:
      - 80:80/tcp
    env_file:
      - .env
  db:
    image: ghcr.io/dfe-digital/trams-development-database:latest
    ports:
      - 1433:1433
    env_file:
      - .env.database
