version: "3.8"
services:
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "./docker-entrypoint.sh dotnet DfE.IdentifiersApi.dll"
    ports:
      - 80:80/tcp
    env_file:
      - .env
